server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ew4df44ed
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
  jpa:
    hibernate:

      ddl-auto: create-drop

    properties:
      hibernate:
        validator:
          apply_to_ddl: false
          autoregister_listeners: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jakarta:
        persistence:
          validation:
            mode: none
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: eugenepodolskiy@gmail.com
    password: flacatdvjosgcbdv

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
